[launcher]
author=Darren Dance
description=Test Addon
version=1.0.0

[ui]
is_visible = false
label = acs demo addon

[package]
id = TA-test
check_for_updates = false

[id]
name = TA-test
version = 1.0.0